" ~/.vim/vimrc

if has('vim_starting')
  call init#rc('init')
  call init#rc('options')
endif

call init#rc('settings')
call init#rc('dein')
call init#rc('solarized')

if !(exists('g:less.loaded') && g:less.loaded ==# 1)
  runtime macros/less.vim
endif

if has('vim_starting')
  colorscheme solarized

  augroup myvimrc
    au ColorScheme * nested call init#on_colors()
    au VimEnter * runtime ftplugin/man.vim
    au VimEnter * nested call init#on_filetype() | syntax enable
  augroup END

  if !empty(argv()) || get(get(g:,'vimpager',{}),'enabled')
    call init#on_filetype()
    syntax enable
  endif
endif
