# hpack docs: https://github.com/sol/hpack
name: xmonad-my
version: 0.0.0
executables:
  xmonad-my:
    main: xmonad.hs
    source-dirs: [., lib]
    ghc-options: -dynamic -v0 -threaded -O -rtsopts
dependencies:
- base
- xmobar >= 0.29.1
- xmonad >= 0.15
- xmonad-contrib >= 0.15
- utf8-string  # via xmonad/-contrib
- X11
- process
- directory
- containers
- unix
- dbus  # MyNotify
ghc-options:
- -Weverything
- -Wno-partial-type-signatures
- -Wno-missing-import-lists
- -Wno-unused-top-binds
default-extensions:
- DeriveDataTypeable
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- PartialTypeSignatures
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
