# File: ~/.config/tmuxp/configs.yaml

session_name: configs
start_directory: "~"
windows:
- window_name: git-dotfiles
  start_directory: "~"
  panes:
  - git status
  - lazygit
- window_name: tmux
  panes:
  - vim -c "cd ~/.config/tmuxp | NERDTree | botright vsplit ~/.tmux.conf"
- window_name: systemd-user
  start_directory: "~/.config/systemd/user"
  panes:
  - watch -n 30 -bcx systemctl --user --failed
  - vim -c NERDTree
- window_name: "~/.config"
  start_directory: "~/.config"
  panes:
  - vim -c NERDTree
- window_name: system
  panes:
  - cd /etc
  - yay -Ps
  - cd ~/.cache/yay
- window_name: xmonad
  start_directory: ~/.xmonad
  layout: main-vertical
  panes:
  - shell_command:
    - vim xmonad.hs
    focus: true
  - ghcid xmonad.hs
  - stack install --file-watch
- window_name: xmonad/ghci
  panes:
  - stack ghci
