# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/samulith/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
resolver: lts-13.5
compiler: ghc-8.6.3
packages: []
extra-deps: []
#- hoogle-5.0.17.5
#- hasktags-0.71.2
